baseURL = 'https://ahmaddzulkarnainyoo-dev.github.io/'
languageCode = 'id-id'
title = 'Antitesis.id'
theme = 'ananke'
themesDir = 'themes'
[params]
  favicon = ""
  description = "Media Antitesis - Filsafat, Teknologi, dan Literasi"
  # Ini biar CSS-nya kepanggil beneran
  custom_css = []
  body_classes = "item-center"
