baseURL = 'https://ahmaddzulkarnainyoo-dev.github.io/'
languageCode = 'en-us'
title = 'Antitesis.id'
theme = 'ananke'

# Pastiin Hugo tau dia harus nyari tema di folder 'themes'
themesDir = 'themes'
canonifyURLs = true
relativeURLs = false
