baseURL = 'https://antitesis-id.netlify.app/'
languageCode = 'en-us'
title = 'Antitesis.id'
theme = 'ananke'

[params]
  background_color_class = "bg-black"
  featured_image = "images/bg-filsafat.jpg"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Politik"
    url = "/categories/politik/"
    weight = 2
  [[menu.main]]
    name = "Hukum"
    url = "/categories/hukum/"
    weight = 3
  [[menu.main]]
    name = "Edukasi"
    url = "/categories/edukasi/"
    weight = 4
  [[menu.main]]
    name = "Tentang Kami"
    url = "/about/"
    weight = 5


