backend:
  name: github
  repo: ahmaddzulkarnainyoo-dev/antitesis-id.github.io
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Berita / Artikel"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Kategori", name: "categories", widget: "select", options: ["Hukum", "Politik", "Edukasi"]}
      - {label: "Gambar Utama", name: "featured_image", widget: "image", required: false}
      - {label: "Isi Berita", name: "body", widget: "markdown"}
