backend:
  name: git-gateway
  branch: main # Pastiin ini branch utama lo

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Postingan Berita"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar Utama", name: "featured_image", widget: "image", required: false}
      - {label: "Isi Berita", name: "body", widget: "markdown"}
